import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import NavLinks from "@/components/NavLinks";
import { Suspense } from "react";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";


const notoSansBengali = Noto_Sans_Bengali({
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSansBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />

        <Suspense fallback={null}>
          <NavLinks />

        </Suspense>
        <Marquee/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
